import {
    GeneratedTypes,
    InterfaceDefinition,
    EnumDefinition,
    TypeAliasDefinition,
    PropertyDefinition,
} from "../types";

export class TypeScriptRenderer {
    private emitRuntime: boolean;

    constructor(options: { emitRuntime?: boolean }) {
        this.emitRuntime = options.emitRuntime || false;
    }

    render(types: GeneratedTypes): string {
        const sections: string[] = [];

        sections.push(this.renderHeader());

        if (this.emitRuntime) {
            sections.push(this.renderRuntimeHelpers());
        }

        if (types.types.size > 0) {
            sections.push(this.renderTypeAliases(types.types));
        }

        if (types.enums.size > 0) {
            sections.push(this.renderEnums(types.enums));
        }

        if (types.interfaces.size > 0) {
            sections.push(this.renderInterfaces(types.interfaces));
        }

        sections.push(this.renderDataverseTypesAggregate(types.interfaces));

        sections.push(this.renderFooter());

        return this.formatOutput(sections.join("\n\n"));
    }

    private renderHeader(): string {
        return `/**
 * Auto-generated TypeScript definitions for Microsoft Dataverse
 * Generated on: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file was automatically generated from Dataverse metadata.
 * To update these types, run: npx dynamics-web-api generate-types
 */

/* eslint-disable */
/* tslint:disable */

declare module "dataverse-types" {`;
    }

    private renderFooter(): string {
        return `}

export as namespace DataverseTypes;
export = DataverseTypes;`;
    }

    private renderRuntimeHelpers(): string {
        return `    /**
     * Runtime helper functions for Dataverse operations
     */
    export namespace Helpers {
        /**
         * Create OData bind reference for a lookup
         */
        export function createReference(collection: string, id: string): string {
            return \`/\${collection}(\${id})\`;
        }

        /**
         * Extract GUID from OData reference
         */
        export function extractId(reference: string): string | null {
            const match = reference.match(/\\(([^)]+)\\)/);
            return match ? match[1] : null;
        }

        /**
         * Format value for OData filter
         */
        export function formatFilterValue(value: any): string {
            if (value === null) return "null";
            if (typeof value === "string") return \`'\${value}'\`;
            if (value instanceof Date) return value.toISOString();
            return String(value);
        }

        /**
         * Build OData query string
         */
        export function buildQuery(params: {
            select?: string[];
            filter?: string;
            orderby?: string;
            top?: number;
            expand?: string[];
        }): string {
            const parts: string[] = [];
            if (params.select?.length) parts.push(\`$select=\${params.select.join(",")}\`);
            if (params.filter) parts.push(\`$filter=\${params.filter}\`);
            if (params.orderby) parts.push(\`$orderby=\${params.orderby}\`);
            if (params.top) parts.push(\`$top=\${params.top}\`);
            if (params.expand?.length) parts.push(\`$expand=\${params.expand.join(",")}\`);
            return parts.length ? \`?\${parts.join("&")}\` : "";
        }
    }`;
    }

    private renderTypeAliases(types: Map<string, TypeAliasDefinition>): string {
        const lines: string[] = ["    // Type Aliases"];

        for (const [_, typeDef] of types) {
            if (typeDef.description) {
                lines.push(`    /** ${typeDef.description} */`);
            }

            if (typeDef.name === "DataverseTypes") {
                lines.push(`    export interface ${typeDef.name} {`);
                lines.push(`${typeDef.type}`);
                lines.push(`    }`);
            } else {
                lines.push(`    export type ${typeDef.name} = ${typeDef.type};`);
            }
        }

        return lines.join("\n");
    }

    private renderEnums(enums: Map<string, EnumDefinition>): string {
        const lines: string[] = ["    // Enumerations"];

        for (const [_, enumDef] of enums) {
            if (enumDef.description) {
                lines.push(`    /** ${enumDef.description} */`);
            }

            lines.push(`    export enum ${enumDef.name} {`);

            for (const member of enumDef.members) {
                if (member.description) {
                    lines.push(`        /** ${member.description} */`);
                }
                const memberName = this.sanitizeEnumMemberName(member.name);
                lines.push(`        ${memberName} = ${member.value},`);
            }

            lines.push(`    }`);
            lines.push("");

            lines.push(`    /** Labels for ${enumDef.name} */`);
            lines.push(`    export const ${enumDef.name}Labels: Record<${enumDef.name}, string> = {`);
            for (const member of enumDef.members) {
                const memberName = this.sanitizeEnumMemberName(member.name);
                lines.push(`        [${enumDef.name}.${memberName}]: "${member.description || member.name}",`);
            }
            lines.push(`    };`);
        }

        return lines.join("\n");
    }

    private renderInterfaces(interfaces: Map<string, InterfaceDefinition>): string {
        const lines: string[] = ["    // Entity Interfaces"];

        const sortedInterfaces = Array.from(interfaces.entries()).sort(([a], [b]) => {
            if (a.endsWith("Create") && !b.endsWith("Create")) return 1;
            if (!a.endsWith("Create") && b.endsWith("Create")) return -1;
            if (a.endsWith("Update") && !b.endsWith("Update")) return 1;
            if (!a.endsWith("Update") && b.endsWith("Update")) return -1;
            return a.localeCompare(b);
        });

        for (const [_, interfaceDef] of sortedInterfaces) {
            if (interfaceDef.description) {
                lines.push(`    /**`);
                lines.push(`     * ${interfaceDef.description}`);
                lines.push(`     */`);
            }

            const extendsClause = interfaceDef.extends?.length 
                ? ` extends ${interfaceDef.extends.join(", ")}`
                : "";

            lines.push(`    export interface ${interfaceDef.name}${extendsClause} {`);

            for (const prop of interfaceDef.properties) {
                lines.push(this.renderProperty(prop));
            }

            lines.push(`    }`);
            lines.push("");
        }

        return lines.join("\n");
    }

    private renderProperty(prop: PropertyDefinition): string {
        const lines: string[] = [];

        if (prop.description) {
            lines.push(`        /** ${prop.description} */`);
        }

        if (prop.deprecated) {
            lines.push(`        /** @deprecated */`);
        }

        const optionalMark = prop.optional ? "?" : "";
        const propName = this.escapePropertyName(prop.name);
        lines.push(`        ${propName}${optionalMark}: ${prop.type};`);

        return lines.join("\n");
    }

    private renderDataverseTypesAggregate(interfaces: Map<string, InterfaceDefinition>): string {
        const entityInterfaces = Array.from(interfaces.keys())
            .filter(name => !name.endsWith("Create") && !name.endsWith("Update") && !name.endsWith("Request") && !name.endsWith("Response"))
            .sort();

        if (entityInterfaces.length === 0) {
            return "";
        }

        const lines: string[] = [
            "    /**",
            "     * Aggregate type containing all entity interfaces",
            "     * Use this for type-safe API operations",
            "     */",
            "    export interface DataverseEntities {",
        ];

        for (const name of entityInterfaces) {
            const propName = name.charAt(0).toLowerCase() + name.slice(1);
            lines.push(`        ${propName}: ${name};`);
        }

        lines.push("    }");

        return lines.join("\n");
    }

    private escapePropertyName(name: string): string {
        if (name.includes("@") || name.includes(".") || name.includes("-")) {
            return `"${name}"`;
        }
        return name;
    }

    private sanitizeEnumMemberName(name: string): string {
        if (/^\d/.test(name)) {
            return `_${name}`;
        }
        
        const sanitized = name.replace(/[^a-zA-Z0-9_]/g, "_");
        
        const reserved = ["break", "case", "catch", "class", "const", "continue", "debugger", 
                         "default", "delete", "do", "else", "enum", "export", "extends", 
                         "false", "finally", "for", "function", "if", "import", "in", 
                         "instanceof", "new", "null", "return", "super", "switch", "this", 
                         "throw", "true", "try", "typeof", "var", "void", "while", "with"];
        
        if (reserved.includes(sanitized.toLowerCase())) {
            return `_${sanitized}`;
        }
        
        return sanitized;
    }

    private formatOutput(content: string): string {
        try {
            const prettier = require("prettier");
            return prettier.format(content, {
                parser: "typescript",
                semi: true,
                singleQuote: false,
                tabWidth: 4,
                useTabs: false,
                trailingComma: "es5",
            });
        } catch {
            return content;
        }
    }
}